### ISSUE TITLE
Assertion error when node reconnects

### ISSUE THREAD

**Issue by njhurst** [bakwc/PySyncObj#1]
If I run two instances of counter, and kill and restart one while the other is operating, I can fairly reliably get this error:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pysyncobj/syncobj.py", line 177, in _autoTickThread
    self._onTick(self.__conf.autoTickPeriod)
  File "/usr/local/lib/python2.7/dist-packages/pysyncobj/syncobj.py", line 247, in _onTick
    self.__poller.poll(timeToWait)
  File "/usr/local/lib/python2.7/dist-packages/pysyncobj/poller.py", line 96, in poll
    self.__descrToCallbacks[descr](descr, eventMask)
  File "/usr/local/lib/python2.7/dist-packages/pysyncobj/node.py", line 79, in __processConnection
    assert descr == self.__conn.fileno()
AssertionError
```

A great project idea though!

**Comment by bakwc** [comment]
Thanks for report! What operation system do you use? Do you have this assert in a restarted instane or in another one (that was not restarted)?

**Comment by bakwc** [comment]
Was able to reproduce it on ubuntu 15.04, fixed. Try a fresh version please.
