### ISSUE TITLE
Exception in ReplLockManager: dictionary changed size during iteration

### ISSUE THREAD

**Issue by bakwc** [bakwc/PySyncObj#102]
```Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/gevent/threading.py", line 177, in run
    super(Thread, self).run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pysyncobj/syncobj.py", line 500, in _autoTickThread
    self._onTick(self.__conf.autoTickPeriod)
  File "/usr/local/lib/python3.6/dist-packages/pysyncobj/syncobj.py", line 577, in _onTick
    res = self.__doApplyCommand(entry[0])
  File "/usr/local/lib/python3.6/dist-packages/pysyncobj/syncobj.py", line 701, in __doApplyCommand
    return self._idToMethod[funcID](*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pysyncobj/syncobj.py", line 1389, in newFunc
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pysyncobj/batteries.py", line 419, in prolongate
    for lockID in self.__locks.keys():
RuntimeError: dictionary changed size during iteration```

**Comment by andrewthetechie** [comment]
Did a new release get build/pushed to pypi with this patch?

I am running 0.3.4, installed with "pip install pysyncobj" and it still encounters this bug
