### ISSUE TITLE
Failed to update leader lock

### ISSUE THREAD

**Issue by alexeymyltsev** [bakwc/PySyncObj#121]
When use raft for patroni after several hours got exception. 
pysyncobj 0.3.6

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs) 
  File "/usr/local/lib/python3.6/dist-packages/pysyncobj/syncobj.py", line 505, in _autoTickThread
    self._onTick(self.__conf.autoTickPeriod)  
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/raft.py", line 251, in _onTick
    super(KVStoreTTL, self)._onTick(timeToWait)
  File "/usr/local/lib/python3.6/dist-packages/pysyncobj/syncobj.py", line 610, in _onTick
    self._checkCommandsToApply()
  File "/usr/local/lib/python3.6/dist-packages/pysyncobj/syncobj.py", line 454, in _checkCommandsToApply
    self.__sendAppendEntries()
  File "/usr/local/lib/python3.6/dist-packages/pysyncobj/syncobj.py", line 1089, in __sendAppendEntries
    nextNodeIndex = self.__raftNextIndex[node]
KeyError: Node('17015')
```

assumption from patroni maintainer:
https://github.com/zalando/patroni/issues/1701#issuecomment-694038999

**Comment by bakwc** [comment]
Thanks for report! I will look at it.

**Comment by alexeymyltsev** [comment]
could you advise, when it will be in pip and which version?

**Comment by bakwc** [comment]
10 minutes

**Comment by bakwc** [comment]
Uploaded, 0.3.7, `pip install --upgrade pysyncobj`. Could you please check if it helped?

**Comment by alexeymyltsev** [comment]
Thank you. I am starting testing right now.

**Comment by alexeymyltsev** [comment]
Looks like it works.  If I find out some problem I will reopen issue. 
Thank you.
