### ISSUE TITLE
Traceback on tick

### ISSUE THREAD

**Issue by schmidtfx** [bakwc/PySyncObj#23]
On the latest release I'm hitting the following issue after modifying the sync object.

```bash
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Library/Python/2.7/site-packages/pysyncobj/syncobj.py", line 228, in _autoTickThread
    self._onTick(self.__conf.autoTickPeriod)
  File "/Library/Python/2.7/site-packages/pysyncobj/syncobj.py", line 300, in _onTick
    self.__tryLogCompaction()
  File "/Library/Python/2.7/site-packages/pysyncobj/syncobj.py", line 783, in __tryLogCompaction
    cluster = self.__otherNodesAddrs + [self.__selfNodeAddr]
TypeError: can only concatenate tuple (not "list") to tuple
```

**Comment by bakwc** [comment]
How can I reproduce it? May be you use old fullDumpFile (created by old version)?

**Comment by schmidtfx** [comment]
I don't have a dump file created yet. However, I can't reproduce it with your code yet. Will see what I can do.

**Comment by bakwc** [comment]
Are you sure that second argument of the SyncObj is list (otherNodeAddrs)? Seems like you a passing tuple to a SyncObj constructor.

**Comment by schmidtfx** [comment]
You are absolutely right. Thanks. Here is what I'm doing: 
I was passing `*partners` into my own constructor and then was just forwarding `partners`.
I had to do `list(partners)`.
