### ISSUE TITLE
Unable to reliably run three counters on localhost

### ISSUE THREAD

**Issue by njhurst** [bakwc/PySyncObj#3]
When I try to run three counters.py:

```
python counters.py 2000 2001 2002
python counters.py 2001 2000 2002
python counters.py 2002 2000 2001
```

killing and restarting the processes randomly I get: 

```
[EXCEPTION] (/usr/local/lib/python2.7/dist-packages/pysyncobj/syncobj.py, 104):
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pysyncobj/syncobj.py", line 95, in __initInTickThread
    self.__bind()
  File "/usr/local/lib/python2.7/dist-packages/pysyncobj/syncobj.py", line 398, in __bind
    self.__socket.bind((host, int(port)))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use
```

I'm wondering if it's just that you need to close the listener more reliably?

**Comment by bakwc** [comment]
Yep, for now it's not very reliable. But syncobj will retry binding port, so it's not a critical issue. Still need to implement a more reliable shut down scheme.
